=== uncefact/spec-unvtd/docs/schemas/unece_PackingList_PackingListCredential_jsonSchema.json
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "issuer": {
      "$ref": "#/$defs/Party",
      "description": ""
    },
    "issuanceDate": {
      "type": "string",
      "format": "date-time",
      "description": ""
    },
    "credentialSubject": {
      "$ref": "#/$defs/PackingList",
      "description": ""
    },
    "id": {
      "type": "string",
      "format": "uri",
      "description": "A unique number for the user"
    }
  },
  "description": "",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$defs": {
    "Party": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "address": {
          "$ref": "#/$defs/Address",
          "description": "The shipping address for the customer where they would like their orders delivered"
        }
      },
      "description": ""
    },
    "Address": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        }
      },
      "description": ""
    },
    "PackingList": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "contractNumber": {
          "type": "string",
          "description": ""
        },
        "invoiceNumber": {
          "type": "string",
          "description": ""
        },
        "issueDate": {
          "type": "string",
          "format": "date",
          "description": ""
        },
        "buyer": {
          "$ref": "#/$defs/Buyer",
          "description": ""
        },
        "invoicee": {
          "$ref": "#/$defs/Carrier",
          "description": ""
        },
        "shipToParty": {
          "$ref": "#/$defs/Consignee",
          "description": ""
        },
        "seller": {
          "$ref": "#/$defs/Seller",
          "description": ""
        },
        "placeOfDelivery": {
          "$ref": "#/$defs/PlaceOfDelivery",
          "description": ""
        },
        "baseportUnloadingLocation": {
          "$ref": "#/$defs/BaseportUnloadingLocation",
          "description": ""
        },
        "transportContractDocumentConditions": {
          "type": "string",
          "description": ""
        }
      },
      "description": "A request to purchase one or more goods"
    },
    "Buyer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "address": {
          "$ref": "#/$defs/Address",
          "description": "The shipping address for the customer where they would like their orders delivered"
        }
      },
      "description": ""
    },
    "Carrier": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "address": {
          "$ref": "#/$defs/Address",
          "description": "The shipping address for the customer where they would like their orders delivered"
        }
      },
      "description": ""
    },
    "Consignee": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "address": {
          "$ref": "#/$defs/Address",
          "description": "The shipping address for the customer where they would like their orders delivered"
        }
      },
      "description": ""
    },
    "Seller": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "address": {
          "$ref": "#/$defs/Address",
          "description": "The shipping address for the customer where they would like their orders delivered"
        }
      },
      "description": ""
    },
    "PlaceOfDelivery": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "unlocode": {
          "type": "string",
          "format": "uri",
          "description": ""
        },
        "address": {
          "$ref": "#/$defs/Address",
          "description": ""
        }
      },
      "description": ""
    },
    "BaseportUnloadingLocation": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "unlocode": {
          "type": "string",
          "format": "uri",
          "description": ""
        },
        "address": {
          "$ref": "#/$defs/Address",
          "description": "The shipping address for the customer where they would like their orders delivered"
        }
      },
      "description": ""
    }
  }
}

=== uncefact/spec-unvtd/docs/schemas/unece_PackingList_PackingListCredential_instance_jsonSchema.json
{
  "issuer": {
    "id": "https://jargon.sh",
    "address": {
      "street": "The quick brown fox jumps over the lazy dog.",
      "city": "The quick brown fox jumps over the lazy dog.",
      "state": "The quick brown fox jumps over the lazy dog.",
      "zip": 12345
    }
  },
  "issuanceDate": "1970-01-01T00:00:00Z",
  "credentialSubject": {
    "contractNumber": "The quick brown fox jumps over the lazy dog.",
    "invoiceNumber": "The quick brown fox jumps over the lazy dog.",
    "issueDate": "1970-01-01",
    "buyer": {
      "id": "https://jargon.sh",
      "address": {
        "street": "The quick brown fox jumps over the lazy dog.",
        "city": "The quick brown fox jumps over the lazy dog.",
        "state": "The quick brown fox jumps over the lazy dog.",
        "zip": 12345
      }
    },
    "invoicee": {
      "id": "https://jargon.sh",
      "address": {
        "street": "The quick brown fox jumps over the lazy dog.",
        "city": "The quick brown fox jumps over the lazy dog.",
        "state": "The quick brown fox jumps over the lazy dog.",
        "zip": 12345
      }
    },
    "shipToParty": {
      "id": "https://jargon.sh",
      "address": {
        "street": "The quick brown fox jumps over the lazy dog.",
        "city": "The quick brown fox jumps over the lazy dog.",
        "state": "The quick brown fox jumps over the lazy dog.",
        "zip": 12345
      }
    },
    "seller": {
      "id": "https://jargon.sh",
      "address": {
        "street": "The quick brown fox jumps over the lazy dog.",
        "city": "The quick brown fox jumps over the lazy dog.",
        "state": "The quick brown fox jumps over the lazy dog.",
        "zip": 12345
      }
    },
    "placeOfDelivery": {
      "unlocode": "https://jargon.sh",
      "address": {
        "street": "The quick brown fox jumps over the lazy dog.",
        "city": "The quick brown fox jumps over the lazy dog.",
        "state": "The quick brown fox jumps over the lazy dog.",
        "zip": 12345
      }
    },
    "baseportUnloadingLocation": {
      "unlocode": "https://jargon.sh",
      "address": {
        "street": "The quick brown fox jumps over the lazy dog.",
        "city": "The quick brown fox jumps over the lazy dog.",
        "state": "The quick brown fox jumps over the lazy dog.",
        "zip": 12345
      }
    },
    "transportContractDocumentConditions": "The quick brown fox jumps over the lazy dog."
  },
  "id": "https://jargon.sh"
}
