=== uncefact/spec-unvtd/docs/schemas/unece_BillOfLading_BillOfLadingCredential_jsonSchema.json
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "issuer": {
      "$ref": "#/$defs/Party",
      "description": ""
    },
    "issuanceDate": {
      "type": "string",
      "format": "date-time",
      "description": ""
    },
    "id": {
      "type": "string",
      "format": "uri",
      "description": ""
    },
    "credentialSubject": {
      "$ref": "#/$defs/BillOfLading",
      "description": ""
    }
  },
  "description": "A request to purchase one or more goods",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$defs": {
    "Party": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "Party",
          "enum": [
            "Party"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        },
        "country": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "BillOfLading": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "BillOfLading",
          "enum": [
            "BillOfLading"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number for the user"
        },
        "billOfLadingNumber": {
          "type": "string",
          "description": ""
        },
        "bookingNumber[]": {
          "type": "string",
          "description": ""
        },
        "issueDate": {
          "type": "string",
          "format": "date",
          "description": ""
        },
        "actualArrivalDate": {
          "type": "string",
          "format": "date",
          "description": ""
        },
        "estimatedTimeOfDeparture": {
          "type": "string",
          "format": "date",
          "description": ""
        },
        "actualDepartureDate": {
          "type": "string",
          "format": "date",
          "description": ""
        },
        "consignmentLoadingDate": {
          "type": "string",
          "format": "date",
          "description": ""
        },
        "estimatedTimeOfArrival": {
          "type": "string",
          "format": "date",
          "description": ""
        },
        "buyer": {
          "$ref": "#/$defs/Buyer",
          "description": ""
        },
        "Importer": {
          "$ref": "#/$defs/Importer",
          "description": ""
        },
        "exporter": {
          "$ref": "#/$defs/Exporter",
          "description": ""
        },
        "carrier": {
          "$ref": "#/$defs/Carrier",
          "description": ""
        },
        "consignee": {
          "$ref": "#/$defs/Consignee",
          "description": ""
        },
        "freightForwarder": {
          "$ref": "#/$defs/FreightForwarder",
          "description": ""
        },
        "notifyParty[]": {
          "$ref": "#/$defs/NotifyParty",
          "description": ""
        },
        "despatchParty": {
          "$ref": "#/$defs/DespatchParty",
          "description": ""
        },
        "consignor": {
          "$ref": "#/$defs/Consignor",
          "description": ""
        },
        "freightPayer": {
          "$ref": "#/$defs/FreightPayer",
          "description": ""
        },
        "shippingDate": {
          "type": "string",
          "format": "date",
          "description": ""
        },
        "particulars": {
          "$ref": "#/$defs/Particulars",
          "description": ""
        },
        "equipment[]": {
          "$ref": "#/$defs/Equipment",
          "description": ""
        }
      },
      "description": ""
    },
    "Buyer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "Buyer",
          "enum": [
            "Buyer"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        },
        "country": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "Importer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "Importer",
          "enum": [
            "Importer"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        },
        "country": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "Exporter": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "Exporter",
          "enum": [
            "Exporter"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        },
        "country": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "Carrier": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "Carrier",
          "enum": [
            "Carrier"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        },
        "country": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "Consignee": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "Consignee",
          "enum": [
            "Consignee"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        },
        "country": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "FreightForwarder": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "FreightForwarder",
          "enum": [
            "FreightForwarder"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        },
        "country": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "NotifyParty": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "NotifyParty",
          "enum": [
            "NotifyParty"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        },
        "country": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "DespatchParty": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "DespatchParty",
          "enum": [
            "DespatchParty"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        },
        "country": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "Consignor": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "Consignor",
          "enum": [
            "Consignor"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        },
        "country": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "FreightPayer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "default": "FreightPayer",
          "enum": [
            "FreightPayer"
          ]
        },
        "id": {
          "type": "string",
          "format": "uri",
          "description": "A unique number that identifies a customer"
        },
        "street": {
          "type": "string",
          "description": "The street component of the address"
        },
        "city": {
          "type": "string",
          "description": "The city compomnent of the address"
        },
        "state": {
          "type": "string",
          "description": "The state component of the address"
        },
        "zip": {
          "type": "number",
          "description": "Zip or postal code for the address"
        },
        "country": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "Particulars": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "descriptionOfGoods": {
          "type": "string",
          "description": ""
        },
        "numberOfPackages": {
          "type": "integer",
          "description": ""
        },
        "commodityCode": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    },
    "Equipment": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uri",
          "description": ""
        },
        "type": {
          "type": "string",
          "description": ""
        }
      },
      "description": ""
    }
  }
}

=== uncefact/spec-unvtd/schemas/unece_BillOfLading_BillOfLadingCredential_instance_jsonSchema.json
{
  "issuer": {
    "id": "https://jargon.sh",
    "street": "The quick brown fox jumps over the lazy dog.",
    "city": "The quick brown fox jumps over the lazy dog.",
    "state": "The quick brown fox jumps over the lazy dog.",
    "zip": 12345,
    "country": "The quick brown fox jumps over the lazy dog."
  },
  "issuanceDate": "1970-01-01T00:00:00Z",
  "id": "https://jargon.sh",
  "credentialSubject": {
    "id": "https://jargon.sh",
    "billOfLadingNumber": "The quick brown fox jumps over the lazy dog.",
    "bookingNumber[]": "The quick brown fox jumps over the lazy dog.",
    "issueDate": "1970-01-01",
    "actualArrivalDate": "1970-01-01",
    "estimatedTimeOfDeparture": "1970-01-01",
    "actualDepartureDate": "1970-01-01",
    "consignmentLoadingDate": "1970-01-01",
    "estimatedTimeOfArrival": "1970-01-01",
    "buyer": {
      "id": "https://jargon.sh",
      "street": "The quick brown fox jumps over the lazy dog.",
      "city": "The quick brown fox jumps over the lazy dog.",
      "state": "The quick brown fox jumps over the lazy dog.",
      "zip": 12345,
      "country": "The quick brown fox jumps over the lazy dog."
    },
    "Importer": {
      "id": "https://jargon.sh",
      "street": "The quick brown fox jumps over the lazy dog.",
      "city": "The quick brown fox jumps over the lazy dog.",
      "state": "The quick brown fox jumps over the lazy dog.",
      "zip": 12345,
      "country": "The quick brown fox jumps over the lazy dog."
    },
    "exporter": {
      "id": "https://jargon.sh",
      "street": "The quick brown fox jumps over the lazy dog.",
      "city": "The quick brown fox jumps over the lazy dog.",
      "state": "The quick brown fox jumps over the lazy dog.",
      "zip": 12345,
      "country": "The quick brown fox jumps over the lazy dog."
    },
    "carrier": {
      "id": "https://jargon.sh",
      "street": "The quick brown fox jumps over the lazy dog.",
      "city": "The quick brown fox jumps over the lazy dog.",
      "state": "The quick brown fox jumps over the lazy dog.",
      "zip": 12345,
      "country": "The quick brown fox jumps over the lazy dog."
    },
    "consignee": {
      "id": "https://jargon.sh",
      "street": "The quick brown fox jumps over the lazy dog.",
      "city": "The quick brown fox jumps over the lazy dog.",
      "state": "The quick brown fox jumps over the lazy dog.",
      "zip": 12345,
      "country": "The quick brown fox jumps over the lazy dog."
    },
    "freightForwarder": {
      "id": "https://jargon.sh",
      "street": "The quick brown fox jumps over the lazy dog.",
      "city": "The quick brown fox jumps over the lazy dog.",
      "state": "The quick brown fox jumps over the lazy dog.",
      "zip": 12345,
      "country": "The quick brown fox jumps over the lazy dog."
    },
    "notifyParty[]": {
      "id": "https://jargon.sh",
      "street": "The quick brown fox jumps over the lazy dog.",
      "city": "The quick brown fox jumps over the lazy dog.",
      "state": "The quick brown fox jumps over the lazy dog.",
      "zip": 12345,
      "country": "The quick brown fox jumps over the lazy dog."
    },
    "despatchParty": {
      "id": "https://jargon.sh",
      "street": "The quick brown fox jumps over the lazy dog.",
      "city": "The quick brown fox jumps over the lazy dog.",
      "state": "The quick brown fox jumps over the lazy dog.",
      "zip": 12345,
      "country": "The quick brown fox jumps over the lazy dog."
    },
    "consignor": {
      "id": "https://jargon.sh",
      "street": "The quick brown fox jumps over the lazy dog.",
      "city": "The quick brown fox jumps over the lazy dog.",
      "state": "The quick brown fox jumps over the lazy dog.",
      "zip": 12345,
      "country": "The quick brown fox jumps over the lazy dog."
    },
    "freightPayer": {
      "id": "https://jargon.sh",
      "street": "The quick brown fox jumps over the lazy dog.",
      "city": "The quick brown fox jumps over the lazy dog.",
      "state": "The quick brown fox jumps over the lazy dog.",
      "zip": 12345,
      "country": "The quick brown fox jumps over the lazy dog."
    },
    "shippingDate": "1970-01-01",
    "particulars": {
      "descriptionOfGoods": "The quick brown fox jumps over the lazy dog.",
      "numberOfPackages": 12345,
      "commodityCode": "The quick brown fox jumps over the lazy dog."
    },
    "equipment[]": {
      "id": "https://jargon.sh",
      "type": "The quick brown fox jumps over the lazy dog."
    }
  }
}
